compartment_id   = "ocid1.tenancy.oc1..aaaaaaaaiq4zp55favmeitmdd4c3lggs57iswzowvwa5k6566whocrhxgbsa"
region           = "sa-santiago-1"
user_ocid        = "ocid1.user.oc1..aaaaaaaanyid33ldcxisfc7vcnnvs3hk2tj7rlc44o3wevaowhvjmklrvb7a"
fingerprint      = ""
tenancy_ocid     = ""
private_key_path = "~/.oci/oci_api_key.pem"
ssh_public_key_file = "~/.oci/oci_api_key_public.pem"